EC.PRM.UI.Web/Controllers/ImportLayoutController.cs
using EC.PRM.LogicaNegocio.Entities;
using EC.PRM.UI.Web.Models;
using EC.PRM.UI.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace EC.PRM.UI.Web.Controllers
{
    public class ImportLayoutController : Controller
    {
        // GET: ImportLayout
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ImportDataFile(string catalog)
        {
            if (System.Web.HttpContext.Current.Session["objUser"] == null)
            {
                Response.Redirect("/Home/Login");
            }

            ImportLayoutModel model = new Models.ImportLayoutModel();

            model.catalogName = catalog;

            Cat_Vendor entVendor = new Cat_Vendor()
            {
                Vendor_Active = true
            };
            model.lstVendor = entVendor.GetCollectionByData();

            return View(model);
        }

        private ImportLayoutModel ImportTarget(
            string path, ImportLayoutModel model, Cat_User objUser)
        {
            try
            {
                List<DataTable> lstData = ExcelReader.GetDataFromExcel(path);
                int numCorrect = 0, numFail = 0;

                foreach (DataTable dtTarget in lstData)
                {
                    Cat_Currency entCurrency = new Cat_Currency()
                    {
                        Currency_Code = dtTarget.TableName
                    };
                    entCurrency = entCurrency.GetFirtByData();

                    if (entCurrency == null)
                    {
                        model.CargadoCorrecto = false;
                        model.Mensajes = "Layout para carga de target incorrecto, favor de verificar.";
                    }

                    var lstTargetExcel = dtTarget.AsEnumerable()
                        .Select(row => new
                        {
                            segment = row.Field<string>("F1"),
                            term12 = row.Field<double?>("12"),
                            term24 = row.Field<double?>("24"),
                            term36 = row.Field<double?>("36"),
                            term48 = row.Field<double?>("48"),
                            term60 = row.Field<double?>("60"),
                            term72 = row.Field<double?>("72"),
                            term80 = row.Field<double?>("80")
                        })
                        .Distinct().ToList();

                    Cat_FinancialTermCollection lstTerm = Cat_FinancialTerm.GetAll();

                    foreach (var targetExcel in lstTargetExcel)
                    {
                        try
                        {
                            Type t = targetExcel.GetType();
                            PropertyInfo[] lp = t.GetProperties();

                            foreach (PropertyInfo p in lp)
                            {
                                Ope_ProfitTarget entTarget = new Ope_ProfitTarget()
                                {
                                    ProfitTarget_Segment = targetExcel.segment.Trim(),
                                    ProfitTarger_CurrencyId = entCurrency.CurrencyId
                                };

                                var v = p.GetValue(targetExcel, null);

                                if (v != null)
                                {
                                    if (!p.Name.Equals("segment"))
                                    {
                                        string monthNum = p.Name.Substring(p.Name.Length - 2, 2);
                                        int month = Convert.ToInt32(monthNum);
                                        int termId = lstTerm.Find(x => x.FinancialTerm_Value == month).FinancialTermId.Value;

                                        entTarget.ProfitTarget_FinacialTermId = termId;
                                        entTarget.ProfitTarget_Active = true;

                                        entTarget = entTarget.GetFirtByData();

                                        if (entTarget != null)
                                        {
                                            entTarget.ProfitTarget_Active = false;
                                            entTarget.Update();
                                        }

                                        entTarget = new Ope_ProfitTarget();
                                        entTarget.ProfitTarget_Segment = targetExcel.segment;
                                        entTarget.ProfitTarger_CurrencyId = entCurrency.CurrencyId;
                                        entTarget.ProfitTarget_FinacialTermId = termId;

                                        entTarget.ProfitTarget_Percentage = Convert.ToDouble(v) * 100;
                                        entTarget.ProfitTarget_UserIdUpload = objUser.UserId;
                                        entTarget.ProfitTarget_DateUpload = DateTime.Now;
                                        entTarget.ProfitTarget_Active = true;
                                        entTarget.Insert();

                                        numCorrect++;
                                    }
                                }
                            }
                        }
                        catch
                        {
                            numFail++;
                        }
                    }
                }

                model.CargadoCorrecto = true;
                model.Mensajes = numCorrect + " registros importados correctamente, " + numFail + " registros no se pudieron importar.";
            }
            catch (Exception ex)
            {
                model.CargadoCorrecto = false;
                model.Mensajes = ex.Message;
            }

            return model;
        }

        private ImportLayoutModel ImportAsset(
            string path, ImportLayoutModel model, string cboVendor, Cat_User objUser)
        {
            try
            {
                List<DataTable> lstData = ExcelReader.GetDataFromExcel(path);
                DataTable dtAsset = lstData.Find(x => x.TableName.Equals("LayoutAsset"));
                int numCorrect = 0, numFail = 0;

                var lstAssetExcel = dtAsset.AsEnumerable()
                        .Select(row => new
                        {
                            collateral = row.Field<string>("CollateralDescription"),
                            brand = row.Field<string>("Brand"),
                            model = row.Field<string>("Model"),
                            description = row.Field<string>("Description"),
                            year = row.Field<double>("Year"),
                            currencyCode = row.Field<string>("Currency")
                        })
                        .Distinct().ToList();

                foreach (var assetExcel in lstAssetExcel)
                {
                    Cat_Asset entAsset = new Cat_Asset()
                    {
                        Asset_Brand = assetExcel.brand,
                        Asset_Model = assetExcel.model,
                        Asset_Description = assetExcel.description,
                        Asset_Year = Convert.ToInt32(assetExcel.year),
                        Asset_Active = true
                    };
                    entAsset = entAsset.GetFirtByData();

                    if (entAsset != null)
                    {
                        numFail++;
                        continue;
                    }

                    Cat_AssetCollateral entColat = new Cat_AssetCollateral()
                    {
                        AssetCollateral_Description = assetExcel.collateral
                    };
                    entColat = entColat.GetFirtByData();

                    if (entColat == null)
                    {
                        entColat = new Cat_AssetCollateral()
                        {
                            AssetCollateral_Description = assetExcel.collateral,
                            AssetCollateral_Active = true
                        };

                        entColat.Insert();

                        Rel_AssetCollateralVendor entGrupoVendor = new Rel_AssetCollateralVendor()
                        {
                            AssetCollateralVendor_AssetCollateralId = entColat.AssetCollateralId,
                            AssetCollateralVendor_VendorId = objUser.User_VendorId
                        };
                        entGrupoVendor.Insert();
                    }

                    Cat_Currency entMoneda = new Cat_Currency()
                    {
                        Currency_Code = assetExcel.currencyCode
                    };

                    if (entMoneda == null)
                    {
                        numFail++;
                        continue;
                    }

                    var lstRV = (from row in dtAsset.AsEnumerable()
                                 where row.Field<string>("CollateralDescription") == assetExcel.collateral &&
                                     row.Field<string>("Brand") == assetExcel.brand &&
                                     row.Field<string>("Model") == assetExcel.model &&
                                     row.Field<string>("Description") == assetExcel.description &&
                                     row.Field<double>("Year") == assetExcel.year
                                 select row).ToList();

                    entAsset = new Cat_Asset()
                    {
                        Asset_AssetCollateralId = entColat.AssetCollateralId,
                        Asset_Brand = assetExcel.brand,
                        Asset_Model = assetExcel.model,
                        Asset_Description = assetExcel.description,

EC.PRM.UI.Web/Views/ImportLayout/ImportAsset.cshtml
@using EC.PRM.LogicaNegocio.Entities;
@model EC.PRM.UI.Web.Models.ImportLayoutModel

@using (Html.BeginForm("ImportDataFile", "ImportLayout", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h3>Activos.</h3>

    <div class="row form-group">
        <div class="col-md-12">
            <table cellpadding="5" cellspacing="5" width="100%">

                <tr>
                    <td>Vendor: </td>
                    <td width="350">
                        <select class="form-control" id="cboVendor" name="cboVendor">
                            <option value="0">--- Selecciona una opción ---</option>
                            @foreach(Cat_Vendor ent in Model.lstVendor)
                            {
                                <option value="@ent.VendorId">@ent.Vendor_Name</option>
                            }
                        </select>
                        <br />
                    </td>
                </tr>
                <tr>
                    <td>Layout: </td>
                    <td width="350">

                        <input type="file" name="postedFile" id="file-2" class="inputfile inputfile-2" data-multiple-caption="{count} files selected" multiple="" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
                        <label for="file-2"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"></path></svg> <span>Elige un archivo</span></label>
                        @Html.Hidden("catalog", Model.catalogName)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>

                        <input type="submit" value="Importar" class="btn btn-primary" />
                    </td>
                </tr>
            </table>

            <br />
            @if (Model.CargadoCorrecto)
            {
            <span style="color:green">@Model.Mensajes</span>
            }
            else
            {
                <span style="color:red">@Model.Mensajes</span>
            }
        </div>
    </div>
}

EC.PRM.UI.Web/Views/ImportLayout/ImportDataFile.cshtml
@model EC.PRM.UI.Web.Models.ImportLayoutModel

@{
    ViewBag.Title = "ImportDataFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("/Scripts/js/ImportLayout.js")

<div class="gtco-section gtco-gray-bg">
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12">
                <div class="animate-box">

                    <h3>Importar datos desde layout.</h3>

                    <label>Aquí puedes cargar de forma masiva los registros de catálogos desde un archivo Excel.</label>
                    <hr class="dottedline">

                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-6 animate-box">
                                @switch (Model.catalogName)
                                {
                                    case "Asset":
                                        Html.RenderPartial("ImportAsset", Model);
                                        break;
                                    case "Target":
                                        Html.RenderPartial("ImportTarget", Model);
                                        break;
                                }
                                

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EC.PRM.UI.Web/Views/ImportLayout/ImportTarget.cshtml
@using EC.PRM.LogicaNegocio.Entities;
@model EC.PRM.UI.Web.Models.ImportLayoutModel

@using (Html.BeginForm("ImportDataFile", "ImportLayout", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h3>Profit target.</h3>

    <div class="row form-group">
        <div class="col-md-12">
            <table cellpadding="5" cellspacing="5" width="100%">

                <tr>
                    <td>Layout: </td>
                    <td width="350">

                        <input type="file" name="postedFile" id="file-2" class="inputfile inputfile-2" data-multiple-caption="{count} files selected" multiple="" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
                        <label for="file-2"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"></path></svg> <span>Elige un archivo</span></label>
                        @Html.Hidden("catalog", Model.catalogName)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>

                        <input type="submit" value="Importar" class="btn btn-primary" />
                    </td>
                </tr>
            </table>

            <br />
            @if (Model.CargadoCorrecto)
            {
                <span style="color:green">@Model.Mensajes</span>
            }
            else
            {
                <span style="color:red">@Model.Mensajes</span>
            }
        </div>
    </div>
}